### PR TITLE
oniro: Add project to list

### PR DESCRIPTION
**Pull request by rzr**
Relate-to: https://gitlab.eclipse.org/eclipse-wg/oniro-wg/proposal-incubation-stage-oniro/proposal-incubation-oniro-marketing/-/issues/22#
Signed-off-by: Philippe Coval <philippe.coval@huawei.com>

### CODE REVIEW

**Comment by rzr** [comment]
I am marking it as draft  because this change depends on so
https://github.com/EclipseFdn/fosdem2021-static/pull/2

**Comment by ericpoirier** [comment]
Sounds good, please change the status once the dependencies are done.

Thanks.

**Comment by rzr** [comment]
ok it should be ready, please merge:

- https://github.com/EclipseFdn/fosdem2021-static/pull/2 (Merged)
- https://github.com/EclipseFdn/fosdem2021-content/pull/5 (Open)

Then I will remove the draft prefix.

Meanwhile i have replaced my default email attached to eclipse account, I am still wondering if it's possible to attach several emails per account?

**Comment by rzr** [comment]
Please merge, then I can do the  next step would be to update gitmodule at https://github.com/FOSDEM/stands-website/

Cc: @toscalix, @gaelblondelle

**Review by ericpoirier — APPROVED** [review]

**Pull request merged**
